sudo: required
dist: trusty

# stages:
#   - test
#   - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix interp -lib hx3compat
  - lix run travix neko -lib hx3compat
  - lix run travix node -lib hx3compat
  - lix run travix python -lib hx3compat
  # - lix run travix flash -lib hx3compat
  # - lix run travix java -lib hx3compat
  # - lix run travix cs -lib hx3compat
  - lix run travix lua -lib hx3compat
  - lix run travix js -lib hx3compat
  - lix run travix php -lib hx3compat
  - lix run travix cpp -lib hx3compat

# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       language: haxe
#       haxe: "3.4.7"
#       os: linux
#       install: skip
#       script: skip
#       env:
#         secure: TODO
#       after_success:
#         - haxelib install travix
#         - haxelib run travix install
#         - haxelib run travix release
