sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
      
install:
  - npm install
  
script:
  - npm run --silent travix interp
  - npm run --silent travix neko
  - npm run --silent travix node
  - npm run --silent travix python
  # - npm run --silent travix flash
  # - npm run --silent travix java
  # - npm run --silent travix cs
  - npm run --silent travix lua
  - npm run --silent travix js
  - npm run --silent travix php
  - npm run --silent travix cpp
